/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsNewRouteImport } from './routes/jobs.new'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as InterviewTokenRouteImport } from './routes/interview.$token'
import { Route as JobsJobIdCompareRouteImport } from './routes/jobs.$jobId.compare'
import { Route as JobsJobIdCandidatesCandidateIdRouteImport } from './routes/jobs.$jobId.candidates.$candidateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewTokenRoute = InterviewTokenRouteImport.update({
  id: '/interview/$token',
  path: '/interview/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdCompareRoute = JobsJobIdCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => JobsJobIdRoute,
} as any)
const JobsJobIdCandidatesCandidateIdRoute =
  JobsJobIdCandidatesCandidateIdRouteImport.update({
    id: '/candidates/$candidateId',
    path: '/candidates/$candidateId',
    getParentRoute: () => JobsJobIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/interview/$token': typeof InterviewTokenRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs/new': typeof JobsNewRoute
  '/jobs/$jobId/compare': typeof JobsJobIdCompareRoute
  '/jobs/$jobId/candidates/$candidateId': typeof JobsJobIdCandidatesCandidateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/interview/$token': typeof InterviewTokenRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs/new': typeof JobsNewRoute
  '/jobs/$jobId/compare': typeof JobsJobIdCompareRoute
  '/jobs/$jobId/candidates/$candidateId': typeof JobsJobIdCandidatesCandidateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/interview/$token': typeof InterviewTokenRoute
  '/jobs/$jobId': typeof JobsJobIdRouteWithChildren
  '/jobs/new': typeof JobsNewRoute
  '/jobs/$jobId/compare': typeof JobsJobIdCompareRoute
  '/jobs/$jobId/candidates/$candidateId': typeof JobsJobIdCandidatesCandidateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/interview/$token'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/jobs/$jobId/compare'
    | '/jobs/$jobId/candidates/$candidateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/interview/$token'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/jobs/$jobId/compare'
    | '/jobs/$jobId/candidates/$candidateId'
  id:
    | '__root__'
    | '/'
    | '/interview/$token'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/jobs/$jobId/compare'
    | '/jobs/$jobId/candidates/$candidateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InterviewTokenRoute: typeof InterviewTokenRoute
  JobsJobIdRoute: typeof JobsJobIdRouteWithChildren
  JobsNewRoute: typeof JobsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$token': {
      id: '/interview/$token'
      path: '/interview/$token'
      fullPath: '/interview/$token'
      preLoaderRoute: typeof InterviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId/compare': {
      id: '/jobs/$jobId/compare'
      path: '/compare'
      fullPath: '/jobs/$jobId/compare'
      preLoaderRoute: typeof JobsJobIdCompareRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
    '/jobs/$jobId/candidates/$candidateId': {
      id: '/jobs/$jobId/candidates/$candidateId'
      path: '/candidates/$candidateId'
      fullPath: '/jobs/$jobId/candidates/$candidateId'
      preLoaderRoute: typeof JobsJobIdCandidatesCandidateIdRouteImport
      parentRoute: typeof JobsJobIdRoute
    }
  }
}

interface JobsJobIdRouteChildren {
  JobsJobIdCompareRoute: typeof JobsJobIdCompareRoute
  JobsJobIdCandidatesCandidateIdRoute: typeof JobsJobIdCandidatesCandidateIdRoute
}

const JobsJobIdRouteChildren: JobsJobIdRouteChildren = {
  JobsJobIdCompareRoute: JobsJobIdCompareRoute,
  JobsJobIdCandidatesCandidateIdRoute: JobsJobIdCandidatesCandidateIdRoute,
}

const JobsJobIdRouteWithChildren = JobsJobIdRoute._addFileChildren(
  JobsJobIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InterviewTokenRoute: InterviewTokenRoute,
  JobsJobIdRoute: JobsJobIdRouteWithChildren,
  JobsNewRoute: JobsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
